---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: website-monitor
  name: website-monitor
  namespace: monitoring
spec:
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
    targetPort: 9100
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: website-monitor
  labels:
    app.kubernetes.io/name: website-monitor
subsets:
  - addresses:
      - ip: 10.0.0.1
      - ip: 10.0.0.2
      - ip: 10.0.0.3
      - ip: 10.0.0.4
    ports:
      - name: metrics
        port: 9100
---
 apiVersion: monitoring.coreos.com/v1
 kind: ServiceMonitor
 metadata:
   labels:
     release: kube-prometheus-stack
     app.kubernetes.io/name: website-monitor
   name: website-monitor
   namespace: monitoring
 spec:
   endpoints:
   - path: /metrics
     port: metrics
   namespaceSelector:
     matchNames:
       - monitoring
   selector:
     matchLabels:
       app.kubernetes.io/name: website-monitor
